package com.capgemini.wsb.fitnesstracker.user.api;

import jakarta.annotation.Nullable;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@ToString

/**
 * Represents a User entity in the system.
 * This class contains all the necessary fields to define a user.
 * The User entity is mapped to the database and holds personal information.
 */
public class User {

    /**
     * Unique identifier for the user.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Nullable
    private Long id;

    /**
     * The first name of the user.
     * This field cannot be null.
     */
    @Column(name = "first_name", nullable = false)
    private String firstName;

    /**
     * The last name of the user.
     * This field cannot be null.
     */
    @Column(name = "last_name", nullable = false)
    private String lastName;

    /**
     * The birthdate of the user.
     * This field cannot be null.
     */
    @Column(name = "birthdate", nullable = false)
    private LocalDate birthdate;

    /**
     * The email address of the user.
     * This field cannot be null and must be unique.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * Constructor to create a new User instance.
     *
     * @param firstName the first name of the user
     * @param lastName  the last name of the user
     * @param birthdate the birthdate of the user
     * @param email     the email address of the user
     */
    public User(
            final String firstName,
            final String lastName,
            final LocalDate birthdate,
            final String email) {

        this.firstName = firstName;
        this.lastName = lastName;
        this.birthdate = birthdate;
        this.email = email;
    }

}

